version: "3.9"
services:
  web:
    build: .
    container_name: "boston_gene"
    environment:
      - FILE_PATH=${FILE_PATH}
      - FILE_SEPARATOR=${FILE_SEPARATOR}
      - PORT=${PORT-8000}
    ports:
    - "8000:8000"
    volumes:
    - ./:/app/